import type { DiscussionPost } from "@/features/community/types";

export const DISCUSSIONS: DiscussionPost[] = [
  {
    id: "roadmap-review-cadence",
    author: { name: "Yasmine B.", avatarSeed: 47 },
    role: "Product Owner",
    timeAgo: "2h",
    category: "Product Management",
    title: "How often does your team run roadmap reviews?",
    body: "We moved from monthly to bi-weekly and stakeholders are happier, but the team feels the planning overhead. Curious what cadence works for other PMs here.",
    likeCount: 24,
    commentCount: 11,
    pinned: true,
  },
  {
    id: "analytics-tool-recs",
    author: { name: "Karim M.", avatarSeed: 13 },
    role: "Engineering Manager",
    timeAgo: "5h",
    category: "Engineering",
    title: "Looking for recommendations on product analytics tools",
    body: "Evaluating Amplitude vs PostHog for a mid-size SaaS product with a small data team. What do you all use, and what convinced you to switch?",
    likeCount: 18,
    commentCount: 9,
  },
  {
    id: "async-standups",
    author: { name: "Nadia F.", avatarSeed: 41 },
    role: "Scrum Master",
    timeAgo: "8h",
    category: "Agile & Scrum",
    title: "Async standups: has it actually worked for your team?",
    body: "We switched to a written async standup in Slack six weeks ago. Attendance is up but I'm not convinced blockers get surfaced fast enough. Real experiences welcome.",
    likeCount: 31,
    commentCount: 17,
  },
  {
    id: "portfolio-review-junior",
    author: { name: "Sofia T.", avatarSeed: 60 },
    role: "Product Designer",
    timeAgo: "11h",
    category: "UX / UI Design",
    title: "Would appreciate a portfolio review before I apply",
    body: "Three years in, mostly B2B dashboards, trying to break into consumer product. Would love a few honest eyes before I start sending applications this week.",
    likeCount: 14,
    commentCount: 6,
  },
  {
    id: "switching-to-pm-from-eng",
    author: { name: "Bilal R.", avatarSeed: 57 },
    role: "Senior Developer",
    timeAgo: "1d",
    category: "Career Growth",
    title: "Switching from engineering to product, six months in",
    body: "Wrote up what surprised me most moving from a dev role into product management at the same company: mostly the stakeholder management, less the technical side.",
    likeCount: 42,
    commentCount: 23,
  },
  {
    id: "discovery-without-budget",
    author: { name: "Meriem H.", avatarSeed: 36 },
    role: "Product Manager",
    timeAgo: "1d",
    category: "Product Management",
    title: "Running discovery interviews without a research budget",
    body: "No dedicated researcher, no paid participant pool. Sharing what's worked for scrappy discovery: warm intros through the community, 20-minute calls, one question at a time.",
    likeCount: 27,
    commentCount: 8,
  },
  {
    id: "onboarding-flow-feedback",
    author: { name: "Farid A.", avatarSeed: 9 },
    role: "UX Designer",
    timeAgo: "2d",
    category: "UX / UI Design",
    title: "Feedback on a 3-step onboarding flow before we ship",
    body: "Trying to cut drop-off on step 2 (permissions request). Would value a second opinion on whether the copy is doing enough to explain why we're asking.",
    likeCount: 9,
    commentCount: 4,
  },
  {
    id: "code-review-culture",
    author: { name: "Yacine D.", avatarSeed: 25 },
    role: "Tech Lead",
    timeAgo: "2d",
    category: "Engineering",
    title: "Building a code review culture on a team that skipped it",
    body: "Inherited a team where PRs were rubber-stamped. Slowly introducing real review without making it feel like a blocker. What's worked for teams that made this shift?",
    likeCount: 22,
    commentCount: 13,
  },
];
